---
alg_name: IM
pretr_epochs: 10
batch_size: 200
shots_per_class: -1  # for data efficiency/few-shot. -1 is all data.
optimizer: sgd
momentum: 0.9
weight_decay: 0
lr: 1.0e-4
epochs: 15

log_freq: 1
val_freq: 1